### Amadeus
@serverHostname = localhost
@serverPort = 3000
@api = /api
@serverUrl = http://{{serverHostname}}:{{serverPort}}
@contentType = application/json

@authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmI4YWE4YWUyNmNkMjEwOGZlZTM4NjAiLCJlbWFpbCI6ImFkbWluQGxvY2FsaG9zdC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjQ3NjQxNzMsImV4cCI6MTcyNDkzNjk3M30.7ashf_fyuHOxoZSxv3S0waeGKL8aA9VrENgQnOsWVXs


# ------------------------------------------------------------
# App
# ------------------------------------------------------------

###
### Get app url
###

GET {{serverUrl}}/pKY-pxUv3G
Content-Type: {{contentType}}

# ------------------------------------------------------------
# Auth
# ------------------------------------------------------------

###
### Post auth
###

POST {{serverUrl}}{{api}}/v1/auth/login
Content-Type: {{contentType}}

{
    "email": "admin@localhost.com",
    "password": "allcontrol"
}

# ------------------------------------------------------------
# Urls
# ------------------------------------------------------------

###
### Get all urls
###


GET {{serverUrl}}{{api}}/v1/urls
Content-Type: {{contentType}}
Authorization: {{authorization}}

###
### Get url by id
###


GET {{serverUrl}}{{api}}/v1/urls/61a60d186d4f2ddb7e71d37d
Content-Type: {{contentType}}
Authorization: {{authorization}}

###
### Post url
###

POST {{serverUrl}}{{api}}/v1/urls
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
  "url": "https://wikipedia.com/"
}

###
### Patch url by id
###

PATCH {{serverUrl}}{{api}}/v1/urls/61a60d5a6d4f2ddb7e71d388
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
  "url": "https://imost.cc/",
  "expires": "2024-08-21T11:02:01.966Z"
}

###
### Delete url by id

DELETE {{serverUrl}}{{api}}/v1/urls/61a2546c2fb60a8b29b8c1a5
Content-Type: {{contentType}}
Authorization: {{authorization}}


###

# ------------------------------------------------------------
# Users
# ------------------------------------------------------------

###
### Get all users
###


GET {{serverUrl}}{{api}}/v1/users
Content-Type: {{contentType}}
Authorization: {{authorization}}

###
### Get one user by id
###


GET {{serverUrl}}{{api}}/v1/users/619cba5cdf45478e26167288
Content-Type: {{contentType}}
Authorization: {{authorization}}

###
### Post user
###


POST {{serverUrl}}{{api}}/v1/users
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "allcontrol",
  "role": "password"
}

###
### Patch user by id
###


PATCH {{serverUrl}}{{api}}/v1/users/61a1e8d6e13429afee2fe022
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
  "name": "John Doe [Edited]",
  "password": "newpassword"
}

###
### Delete user by id
###


DELETE {{serverUrl}}{{api}}/v1/users/66b8a4df3fc05570e035118a
Content-Type: {{contentType}}
Authorization: {{authorization}}

###
###
###